version: '3.6'
services:
  gateway:
    image: 'cr.ghanima.net/applications/nbdkit-s3-gateway/nbdkit:latest'
    restart: always
    hostname: 'nbdkit-S3-gateway'
    environment:
      TZ: Australia/Melbourne
      # S3_ENDPOINT_URL must include the trailing "/"
      S3_ENDPOINT_URL: https://s3.ap-southeast-2.wasabisys.com/
      S3_ACCESSKEY: ${S3_ACCESSKEY}
      S3_SECRETKEY: ${S3_SECRETKEY}
      S3_BUCKET: ${S3_BUCKET}
      # Files in the bucket will be prefixed with this string
      S3_KEY: disk
      # Size of the files/blocks that will be stored in S3
      S3_OBJECT_SIZE: 128k
      # Total size of the virtual block device
      DEVICE_SIZE: 500G
    ports:
      - '9001:9001'
      - '9002:9002'
