version: '3.6'
services:
  omnibus:
    image: 'cr.ghanima.net/applications/nbdkit-s3-gateway/nbdkit:latest'
    restart: always
    hostname: 'nbdkit-S3-gateway'
    environment:
      TZ: Australia/Melbourne
      S3_ENDPOINT_URL: https://s3.ap-southeast-2.wasabisys.com
      S3_ACCESSKEY: O17PZMHJNZJ2PIVWPAMC
      S3_SECRETKEY: 7EiFRfOmj91iIahSVMm3ckIppzUCXl3LDPBsPQgd
      S3_BUCKET: syncoid
      # Files in the bucket will be prefixed with this string
      S3_KEY: disk
      # Size of the files/blocks that will be stored in S3
      S3_OBJECT_SIZE: 1M
      # Total size of the virtual block device
      S3_SIZE: 500G
    # ports:
    #   - '80:80'
